export { default as BrandStoryPage } from './BrandStoryPage'
export { default as BriefPage } from './BriefPage'
export { default as LandingPage } from './LandingPage'
export { default as PrivacyPage } from './PrivacyPage'
export { default as TermsPage } from './TermsPage'
export { default as WelcomePage } from './WelcomePage'
