-- Meta Pixel events tracking
-- Stores attribution data from Facebook/Meta ad conversions
-- Allows you to correlate ad performance with your own analytics

create table if not exists public.meta_pixel_events (
  id bigint generated by default as identity primary key,

  -- Event identification
  event_type text not null, -- 'purchase', 'add_to_cart', etc.
  event_id text not null, -- Meta's unique event ID
  pixel_id text not null, -- Meta Pixel ID

  -- Commerce data
  content_ids text[], -- Shopify product IDs
  value numeric not null, -- Purchase/value amount
  currency text not null default 'GBP',
  num_items integer,

  -- Attribution fields (for ad performance analysis)
  fbclid text, -- Facebook Click ID (ad click identifier)
  fbc text, -- Facebook click parameter
  fbp text, -- Facebook browser parameter

  -- Timestamps
  timestamp timestamptz not null,
  created_at timestamptz default now(),

  -- Raw payload (for debugging/future analysis)
  raw_data jsonb
);

-- Indexes for common queries
create index if not exists idx_meta_pixel_events_event_type on public.meta_pixel_events(event_type);
create index if not exists idx_meta_pixel_events_timestamp on public.meta_pixel_events(timestamp desc);
create index if not exists idx_meta_pixel_events_event_id on public.meta_pixel_events(event_id);
create index if not exists idx_meta_pixel_events_pixel_id on public.meta_pixel_events(pixel_id);
create index if not exists idx_meta_pixel_events_fbclid on public.meta_pixel_events(fbclid) where fbclid is not null;

-- Add comment
comment on table public.meta_pixel_events is 'Stores Meta Pixel conversion events for ad attribution and performance analysis';
comment on column public.meta_pixel_events.fbclid is 'Facebook Click ID - links to specific ad impressions and clicks';
comment on column public.meta_pixel_events.content_ids is 'Shopify product IDs in the conversion';
comment on column public.meta_pixel_events.raw_data is 'Complete Meta webhook payload for auditing/debugging';

-- Enable Row Level Security
alter table public.meta_pixel_events enable row level security;

-- Grant access (authenticated users can't see, only service role)
grant usage on schema public to anon, authenticated;
grant select on public.meta_pixel_events to anon, authenticated;

-- Only service role can insert (webhook endpoint uses service role)
grant insert on public.meta_pixel_events to service_role;
